### ISSUE TITLE
Restrict products on the site

### ISSUE THREAD

**Issue by bsimpson53** [newcrossfoodcoop/nxfc#67]
Products should be ignored or unpublished if they are:

* FROZEN
* CHILLED
* Contain Alcohol
* Do not exist in price feed

- [x] newcrossfoodcoop/nxfc_catalogue#9
- [x] newcrossfoodcoop/nxfc_catalogue#3
- [x] newcrossfoodcoop/nxfc_catalogue#4
